require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/claimant/questions", type: :request do
  let(:user) { create(:user, :claimant) }

  before do
    sign_in user
  end

  # This should return the minimal set of attributes required to create a valid
  # Question. As you add validations to Question, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      title: "Test Question",
      body: "Test Body",
      category: "general",
      status: "open"
    }
  }

  let(:invalid_attributes) {
    {
      title: "",
      body: "",
      category: nil,
      status: nil
    }
  }

  describe "GET /show" do
    it "renders a successful response" do
      question = create(:question, user: user)
      get claimant_question_url(question)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_claimant_question_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      question = create(:question, user: user)
      get edit_claimant_question_url(question)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Question" do
        expect {
          post claimant_questions_url, params: { question: valid_attributes }
        }.to change(Question, :count).by(1)
      end

      it "redirects to the created question" do
        post claimant_questions_url, params: { question: valid_attributes }
        expect(response).to redirect_to(claimant_root_path)
      end
    end

    context "with invalid parameters" do
      it "does not create a new Question" do
        expect {
          post claimant_questions_url, params: { question: invalid_attributes }
        }.to change(Question, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post claimant_questions_url, params: { question: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested question" do
        question = create(:question, user: user)
        patch claimant_question_url(question), params: { question: new_attributes }
        question.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the question" do
        question = create(:question, user: user)
        patch claimant_question_url(question), params: { question: new_attributes }
        question.reload
        expect(response).to redirect_to(claimant_root_path)
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        question = create(:question, user: user)
        patch claimant_question_url(question), params: { question: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested question" do
      question = create(:question, user: user)
      expect {
        delete claimant_question_url(question)
      }.to change(Question, :count).by(-1)
    end

    it "redirects to the questions list" do
      question = create(:question, user: user)
      delete claimant_question_url(question)
      expect(response).to redirect_to(claimant_root_url)
    end
  end
end
